var annotated_dup =
[
    [ "AssimpPerse", null, [
      [ "MATERIAL", "struct_assimp_perse_1_1_m_a_t_e_r_i_a_l.html", null ],
      [ "SUBSET", "struct_assimp_perse_1_1_s_u_b_s_e_t.html", null ],
      [ "VERTEX", "struct_assimp_perse_1_1_v_e_r_t_e_x.html", null ]
    ] ],
    [ "Collision", null, [
      [ "AABB", "struct_collision_1_1_a_a_b_b.html", null ],
      [ "Line", "struct_collision_1_1_line.html", null ],
      [ "Plane", "struct_collision_1_1_plane.html", null ],
      [ "Polygon", "struct_collision_1_1_polygon.html", null ],
      [ "Segment", "struct_collision_1_1_segment.html", null ],
      [ "Sphere", "struct_collision_1_1_sphere.html", null ]
    ] ],
    [ "Application", "class_application.html", null ],
    [ "Arrow", "class_arrow.html", "class_arrow" ],
    [ "Camera", "class_camera.html", "class_camera" ],
    [ "FadeAnimation", "class_fade_animation.html", "class_fade_animation" ],
    [ "Game", "class_game.html", null ],
    [ "GolfBall", "class_golf_ball.html", "class_golf_ball" ],
    [ "Ground", "class_ground.html", "class_ground" ],
    [ "Hole1Scene", "class_hole1_scene.html", null ],
    [ "Hole2Scene", "class_hole2_scene.html", null ],
    [ "Hole3Scene", "class_hole3_scene.html", null ],
    [ "IndexBuffer", "class_index_buffer.html", null ],
    [ "Input", "class_input.html", null ],
    [ "LIGHT", "struct_l_i_g_h_t.html", null ],
    [ "MATERIAL", "struct_m_a_t_e_r_i_a_l.html", null ],
    [ "Material", "class_material.html", null ],
    [ "Mesh", "class_mesh.html", null ],
    [ "MeshRenderer", "class_mesh_renderer.html", null ],
    [ "Object", "class_object.html", "class_object" ],
    [ "Pole", "class_pole.html", "class_pole" ],
    [ "Renderer", "class_renderer.html", null ],
    [ "ResultScene", "class_result_scene.html", null ],
    [ "Scene", "class_scene.html", null ],
    [ "Shader", "class_shader.html", null ],
    [ "Sphere", "class_sphere.html", "class_sphere" ],
    [ "StaticMesh", "class_static_mesh.html", null ],
    [ "stbi_io_callbacks", "structstbi__io__callbacks.html", null ],
    [ "SUBSET", "struct_s_u_b_s_e_t.html", null ],
    [ "TestCube", "class_test_cube.html", "class_test_cube" ],
    [ "TestModel", "class_test_model.html", "class_test_model" ],
    [ "TestPlane", "class_test_plane.html", null ],
    [ "Texture", "class_texture.html", null ],
    [ "Texture2D", "class_texture2_d.html", "class_texture2_d" ],
    [ "TitleScene", "class_title_scene.html", null ],
    [ "VERTEX_3D", "struct_v_e_r_t_e_x__3_d.html", null ],
    [ "VertexBuffer", "class_vertex_buffer.html", null ]
];